// ── FESTIVAL CONFIG ──
window.FESTIVAL_CONFIG={
  id:'sonar26',
  name:'SÓNAR 2026',
  location:'Barcelona · Fira Gran Via',
  startDate:'2026-06-18',
  dateRange:{zh:'6月 18—20 日',zht:'6月 18—20 日',es:'18—20 JUN',ca:'18—20 JUN',en:'JUN 18—20'},
  duration:{zh:'3 天',zht:'3 天',es:'3 días',ca:'3 dies',en:'3 days'},
  faqUrl:'https://sonar.es/',
  defaultDay:'thu',
  weatherLat:41.3574,weatherLon:2.1267,
};

// ── STAGE DATA ──
var ST={
  "SonarVillage by Estrella Damm":{color:"#F5A623",bg:"#1a0e00cc",e:"🌐",s:"Village"},
  "SonarPark":                    {color:"#00E87A",bg:"#001a0acc",e:"🌿",s:"Park"},
  "SonarHall":                    {color:"#4D9FFF",bg:"#00112acc",e:"🏟",s:"Hall"},
  "SonarCar":                     {color:"#FF5500",bg:"#1a0c00cc",e:"🚗",s:"Car"},
  "SonarClub":                    {color:"#CC00FF",bg:"#14001acc",e:"⚡",s:"Club"},
  "SonarLab x Rinse":             {color:"#FF0080",bg:"#1a0015cc",e:"📻",s:"Lab×Rinse"},
};

var HOTSPOTS={};

var DAYS=[
  {key:"thu",label:"Thu 6/18",date:"2026-06-18",sub:"day1",shows:[
    {stage:"SonarVillage by Estrella Damm",time:"17:00",end:"18:00",artist:"Loli Zazou"},
    {stage:"SonarPark",                    time:"18:00",end:"19:00",artist:"La Sofy"},
    {stage:"SonarVillage by Estrella Damm",time:"18:10",end:"19:10",artist:"Arp Frique & The Perpetual Singers"},
    {stage:"SonarHall",                    time:"18:20",end:"19:05",artist:"MERCÈ presents SHOW SIMULATOR"},
    {stage:"SonarCar",                     time:"19:00",end:"00:00",artist:"Speedy J presents STOOR Live with Colin Benders, Nadia Struiwigh, Reeko, and .VRIL"},
    {stage:"SonarPark",                    time:"19:10",end:"19:55",artist:"Metrika"},
    {stage:"SonarVillage by Estrella Damm",time:"19:20",end:"20:10",artist:"Mina & Bryte"},
    {stage:"SonarHall",                    time:"19:50",end:"20:50",artist:"Scaler"},
    {stage:"SonarPark",                    time:"20:05",end:"21:05",artist:"Fukcnormal"},
    {stage:"SonarVillage by Estrella Damm",time:"20:20",end:"21:40",artist:"MALUGI b2b Benwal"},
    {stage:"SonarHall",                    time:"20:55",end:"21:50",artist:"The Hacker"},
    {stage:"SonarPark",                    time:"21:15",end:"22:30",artist:"Clementaum b2b LAZA"},
    {stage:"SonarVillage by Estrella Damm",time:"21:50",end:"23:05",artist:"Lady Shaka b2b Tash LC"},
    {stage:"SonarHall",                    time:"21:55",end:"22:55",artist:"Cabaret Voltaire"},
    {stage:"SonarPark",                    time:"22:40",end:"00:00",artist:"Boys Noize"},
    {stage:"SonarHall",                    time:"23:00",end:"23:55",artist:"Oriana"},
    {stage:"SonarVillage by Estrella Damm",time:"23:10",end:"01:00",artist:"KETTAMA"},
    {stage:"SonarHall",                    time:"00:00",end:"01:00",artist:"Daniel Avery live"},
    {stage:"SonarPark",                    time:"00:10",end:"01:30",artist:"Alba Franch"},
    {stage:"SonarVillage by Estrella Damm",time:"01:05",end:"03:00",artist:"Chris Stussy"},
  ]},
  {key:"fri",label:"Fri 6/19",date:"2026-06-19",sub:"day2",shows:[
    {stage:"SonarVillage by Estrella Damm",time:"17:00",end:"18:30",artist:"Afri K"},
    {stage:"SonarPark",                    time:"18:00",end:"18:45",artist:"GlorySixVain"},
    {stage:"SonarHall",                    time:"18:30",end:"19:15",artist:"Ani in the Hall present Intel·ligència Romàntica"},
    {stage:"SonarVillage by Estrella Damm",time:"18:35",end:"20:05",artist:"Maz"},
    {stage:"SonarPark",                    time:"18:55",end:"20:25",artist:"Baby Pantera presents Desidia"},
    {stage:"SonarHall",                    time:"20:00",end:"20:50",artist:"Daito Manabe"},
    {stage:"SonarCar",                     time:"20:00",end:"03:00",artist:"Speedy J presents STOOR Live with FJAAK, KiNK and Nene H"},
    {stage:"SonarVillage by Estrella Damm",time:"20:15",end:"21:15",artist:"Kelis"},
    {stage:"SonarLab x Rinse",             time:"20:30",end:"21:45",artist:"Olivia Babe"},
    {stage:"SonarPark",                    time:"20:35",end:"21:35",artist:"Cutemobb"},
    {stage:"SonarHall",                    time:"20:55",end:"21:55",artist:"Beatrix Weapons presents BO$$Y OF MUSIC live"},
    {stage:"SonarClub",                    time:"21:00",end:"21:50",artist:"Zuri"},
    {stage:"SonarVillage by Estrella Damm",time:"21:25",end:"23:10",artist:"Cormac"},
    {stage:"SonarPark",                    time:"21:45",end:"23:15",artist:"TAYHANA & MissLupe"},
    {stage:"SonarLab x Rinse",             time:"21:50",end:"23:20",artist:"riria"},
    {stage:"SonarClub",                    time:"22:00",end:"23:00",artist:"Skepta"},
    {stage:"SonarHall",                    time:"22:00",end:"23:00",artist:"YHWH Nailgun"},
    {stage:"SonarHall",                    time:"23:05",end:"00:05",artist:"GOTH-TRAD"},
    {stage:"SonarClub",                    time:"23:10",end:"00:45",artist:"Funk Tribu"},
    {stage:"SonarVillage by Estrella Damm",time:"23:20",end:"00:20",artist:"SBTRKT live"},
    {stage:"SonarPark",                    time:"23:25",end:"00:40",artist:"Perra Inmunda"},
    {stage:"SonarLab x Rinse",             time:"23:30",end:"00:30",artist:"Nia Archives"},
    {stage:"SonarHall",                    time:"00:10",end:"01:10",artist:"Reinier Zonneveld presents R2 (b2b AI, Holographic AV)"},
    {stage:"SonarVillage by Estrella Damm",time:"00:30",end:"01:35",artist:"Arthi"},
    {stage:"SonarLab x Rinse",             time:"00:40",end:"02:20",artist:"Dillinja b2b Doc Scott ft Medic MC"},
    {stage:"SonarPark",                    time:"00:50",end:"02:10",artist:"RONI"},
    {stage:"SonarClub",                    time:"00:55",end:"02:25",artist:"Charlotte de Witte presents The Resistance"},
    {stage:"SonarHall",                    time:"01:15",end:"02:25",artist:"Nina GGG"},
    {stage:"SonarVillage by Estrella Damm",time:"01:45",end:"03:15",artist:"Sammy Virji"},
    {stage:"SonarPark",                    time:"02:20",end:"03:20",artist:"Miss Bashful"},
    {stage:"SonarLab x Rinse",             time:"02:30",end:"03:45",artist:"ꩧ IceMorph ✧"},
    {stage:"SonarHall",                    time:"02:30",end:"03:45",artist:"Jesuz X b2b Ne/Re/A"},
    {stage:"SonarClub",                    time:"02:35",end:"04:05",artist:"DJ Gigola"},
    {stage:"SonarVillage by Estrella Damm",time:"03:25",end:"04:55",artist:"Kilopatrah Jones"},
    {stage:"SonarPark",                    time:"03:30",end:"06:00",artist:"DJ AYA"},
    {stage:"SonarHall",                    time:"03:50",end:"05:00",artist:"Amanda Mussi"},
    {stage:"SonarLab x Rinse",             time:"03:55",end:"05:25",artist:"Addison Groove"},
    {stage:"SonarClub",                    time:"04:15",end:"05:35",artist:"Sara Landry"},
    {stage:"SonarVillage by Estrella Damm",time:"05:00",end:"07:00",artist:"MK (Marc Kinchen) b2b TSHA"},
    {stage:"SonarLab x Rinse",             time:"05:30",end:"07:00",artist:"Amaliah b2b Pangaea"},
    {stage:"SonarClub",                    time:"05:45",end:"07:00",artist:"Daria Kolosova"},
  ]},
  {key:"sat",label:"Sat 6/20",date:"2026-06-20",sub:"day3",shows:[
    {stage:"SonarVillage by Estrella Damm",time:"17:00",end:"18:05",artist:"SYSTEMA"},
    {stage:"SonarPark",                    time:"18:00",end:"18:40",artist:"TAWA"},
    {stage:"SonarVillage by Estrella Damm",time:"18:10",end:"19:40",artist:"Colleen 'Cosmo' Murphy presents Cosmodelica"},
    {stage:"SonarHall",                    time:"18:30",end:"19:20",artist:"30drop presents Insight Into Mind and Space"},
    {stage:"SonarPark",                    time:"18:50",end:"20:50",artist:"Mercromina Club"},
    {stage:"SonarVillage by Estrella Damm",time:"19:45",end:"21:15",artist:"nimino DJ set"},
    {stage:"SonarCar",                     time:"20:00",end:"03:00",artist:"Speedy J presents STOOR Live with Dasha Rush, Luke Slater, Mathew Jonson, and Ø [Phase]"},
    {stage:"SonarHall",                    time:"20:05",end:"21:05",artist:"ROLROLROL"},
    {stage:"SonarLab x Rinse",             time:"20:30",end:"21:40",artist:"ISA"},
    {stage:"SonarClub",                    time:"21:00",end:"21:50",artist:"Ático Corp. & R.I.P. Bestia present UFC (U n F uturo C reible) live"},
    {stage:"SonarPark",                    time:"21:00",end:"21:40",artist:"Main Costa presents Ugly Trap Better"},
    {stage:"SonarHall",                    time:"21:10",end:"22:10",artist:"Sónia Trópicos"},
    {stage:"SonarVillage by Estrella Damm",time:"21:25",end:"22:55",artist:"Carlita"},
    {stage:"SonarLab x Rinse",             time:"21:40",end:"23:00",artist:"Akua"},
    {stage:"SonarPark",                    time:"21:50",end:"23:20",artist:"Tedesco"},
    {stage:"SonarClub",                    time:"22:00",end:"23:15",artist:"The Prodigy"},
    {stage:"SonarHall",                    time:"22:15",end:"23:00",artist:"Namasenda"},
    {stage:"SonarHall",                    time:"23:05",end:"00:05",artist:"Takuya Nakamura"},
    {stage:"SonarLab x Rinse",             time:"23:10",end:"00:25",artist:"DJ MARIA."},
    {stage:"SonarVillage by Estrella Damm",time:"23:15",end:"00:25",artist:"WhoMadeWho live"},
    {stage:"SonarClub",                    time:"23:25",end:"00:40",artist:"Ogazón"},
    {stage:"SonarPark",                    time:"23:30",end:"00:50",artist:"DPR CREAM & DPR ARTIC"},
    {stage:"SonarHall",                    time:"00:10",end:"01:10",artist:"Two Shell"},
    {stage:"SonarVillage by Estrella Damm",time:"00:35",end:"02:05",artist:"LOVEFOXY"},
    {stage:"SonarLab x Rinse",             time:"00:35",end:"01:35",artist:"Wata Igarashi live"},
    {stage:"SonarClub",                    time:"00:50",end:"02:20",artist:"Dom Dolla"},
    {stage:"SonarPark",                    time:"01:00",end:"02:40",artist:"Migal"},
    {stage:"SonarHall",                    time:"01:15",end:"02:25",artist:"Yasmin"},
    {stage:"SonarLab x Rinse",             time:"01:45",end:"03:45",artist:"FJAAK x Kittin live"},
    {stage:"SonarVillage by Estrella Damm",time:"02:15",end:"03:35",artist:"Modeselektor live"},
    {stage:"SonarClub",                    time:"02:30",end:"03:50",artist:"Joy Orbison"},
    {stage:"SonarHall",                    time:"02:30",end:"03:45",artist:"Mousse T."},
    {stage:"SonarPark",                    time:"02:50",end:"03:50",artist:"Ciara Cuvé"},
    {stage:"SonarVillage by Estrella Damm",time:"03:45",end:"05:25",artist:"Gerd Janson b2b Marcel Dettmann"},
    {stage:"SonarHall",                    time:"03:50",end:"05:00",artist:"Melvo Baptiste"},
    {stage:"SonarLab x Rinse",             time:"03:55",end:"05:25",artist:"SALOME"},
    {stage:"SonarPark",                    time:"04:00",end:"06:00",artist:"PETERBLUE"},
    {stage:"SonarClub",                    time:"04:00",end:"05:30",artist:"Amelie Lens presents AURA"},
    {stage:"SonarVillage by Estrella Damm",time:"05:30",end:"07:00",artist:"CARBS: Ketiov & Fernanda Arrau"},
    {stage:"SonarLab x Rinse",             time:"05:30",end:"07:00",artist:"Danielle b2b Ryan Elliott"},
    {stage:"SonarClub",                    time:"05:35",end:"07:00",artist:"ANNË & Sera J"},
  ]},
];
