// ── I18N ──
var LANGS={
  zh:{
    city:"Barcelona · Parc del Fòrum · Junio 2026",
    now:"▶ 正在演出",next:"⏭ 下一场",remaining:"剩余",startsIn:"后开始",
    sort:"排序",byTime:"时间",byName:"名称",catAll:"全部",catMusic:"音乐",catArt:"艺术与社会",catActivity:"活动",
    favs:"💖 我的收藏",noFavs:"还没有收藏的艺人",
    headliner:"HEADLINER",live:"● LIVE",
    mapHint:"双指缩放 · 点击舞台查看演出",reset:"复位",noShows:"今天暂无演出",mapOfficial:"点击查看官网高清地图",
    myEmpty:"💖 收藏艺人后\n在这里查看你的专属行程",myTitle:"我的行程",conflict:"时间冲突",
    opening:"开幕日",day1:"第一天",day2:"第二天",day3:"第三天",bits:"Bits",free:"免费",
    infoTitle:"实用信息",
    doorsH:"开门时间",doorsBody:"主场地 Parc del Fòrum 每天约 16:00 开门，演出持续至次日 05:00–06:00。周三开幕日（6/3）为免费活动，约 17:00 起。",
    transitH:"交通",metroLine:"地铁 L4（黄线）",metroStop:"El Maresme–Fòrum（步行至 Rambla Prim 约1分钟）· Selva de Mar（步行至 Carrer de Pujades 约12分钟）",
    nightbus:"夜巴士 N6 / N7 / N28",nightbusDesc:"23:00–06:00，可达市中心（Pl. Catalunya）",
    shuttle:"摆渡车（返程）",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · 持通票或单日票可乘 · AccessTicket App 预约（€3/程）\n→ Taulat：周四 00:00–05:00 · 周五 02:00–06:00 · 周六 03:00–06:00\n→ Plataforma Marina：周四至六 01:00–04:00",
    bikeH:"免费单车停车场",bikeDesc:"Plaça de Leonardo da Vinci（Fòrum）· 免费，有限容量\n周三 15:30–00:00 · 周四 14:30–07:00 · 周五六 15:00–07:00 · 周日 13:30–00:00",
    bicing:"Bicing 共享单车",bicingDesc:"场地周边站点：Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat 等",
    taxi:"的士（返程）",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant（至凌晨 01:00）",
    metroHours:"周一至四 05:00–00:00 · 周五 05:00–02:00 · 周六 24小时不停",tramLine:"电车 T4 线",tramStop:"Fòrum 站 · 周三末班 00:00 · 周四至日通宵不停",daybus:"日间公交 H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"从市中心沿海滨步行约60分钟，地中海美景相伴",
    banH:"禁带物品",
    banItems:["玻璃容器","专业相机/摄像机（单反等；胶片/卡片机除外）","自拍杆","无人机","宠物（导盲犬除外）"],
    allowItems:["食物（非玻璃容器）","塑料瓶装水（≤50cl，无盖）","自带塑料杯（≤40cl）","胶片/卡片/一次性相机","小型手提包（A4 大小以内）","雨衣/防晒霜","处方药（携带证明）"],
    banLabel:"禁止携带",allowLabel:"允许携带",
    weatherH:"天气预报",
    weatherNote:"六月初的巴塞罗那天气多变——暴雨过后，气温已降至约 21°C。建议携带防水外套或雨披，以及额外一件外套应对凌晨场。场地内有防晒霜取用站。出门前记得查看天气预报。",
    tipsH:"实用小贴士",
    tips:["AccessTicket 手环需在入口激活，请留出排队时间","现金充值点分布在场地各处（仅 AccessTicket 消费）","免费饮水站全场分布，自带空瓶可节省开支","Nobody Is Normal 安全站提供紧急援助","免费水点高峰时段排队较长。建议换舞台时顺手补满水瓶，不要等口渴了再去"],
    emergH:"紧急援助",
    emergItems:["紧急电话：112","安全站：主入口及各主舞台两侧均设有援助点","与同伴走散时：在主舞台正前方集合"],
    ticketsH:"门票",
    ticketSalesBody:"官方购票渠道：Fever App（iOS/Android）和 AccessTicket（支持分期付款）。门票可在 AccessTicket 中转让（未使用且未关联活动预约）。无需打印——直接用 AccessTicket App 扫码验票。",
    ticketTypesBody:"Parc del Fòrum 仅提供三日通票和单日票，无单场演出票。",
    ticketQRBody:"二维码仅允许入场一次，请妥善保管。不要截图发给他人，不要在社交媒体发布。",
    minorsH:"未成年人",
    minor12:"12岁及以下（含）：免票，需在 Fever 领取免费票，由父母或法定监护人陪同（携带证件及本人门票）。",
    minor1315:"13–15岁：需购买未成年人票，必须由父母或法定监护人陪同（不含兄弟姐妹或其他亲属）。",
    minor1617:"16–17岁：购买青少年票后可独立入场（无需陪同）。部分场馆演出需年满18岁。",
    accessH:"无障碍服务（PRM）",
    accessBody:"行动不便及有特殊需求人士可通过快速通道入场（可携带一名陪伴者）。各主要舞台均设专属观看区及无障碍卫生间。",
    accessEmail:"accessibility@primaverasound.com",
    payH:"场内支付方式",
    payBody:"支持信用/借记卡（Visa 及 Mastercard；不接受美国运通）和 AccessTicket 钱包。",
    lostH:"失物招领",
    lostBody:"节日期间失物统一送至外部信息点，可就近前往或填写失物表格。节日结束后未认领物品移交至 Guàrdia Urbana de Poblenou（Carrer d'Espronceda, 148）。",
    faqH:"官方常见问题",faqLink:"查看完整官方 FAQ",
    navHome:"首页",navSchedule:"演出表",navMap:"地图",navFavs:"收藏",navInfo:"实用信息",navTheme:"主题",navLang:"语言",
    showPast:"场已结束",hidePast:"隐藏已结束",more:"更多",collapse:"收起",
    disclaimer:"本站为乐迷自制的非官方指南，与 Primavera Sound S.L. 无任何关联。<br>所有商标归各自所有者所有。<br>演出信息仅供参考，请以<a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">官方网站</a>为准。<br>反馈或纠错请联系：",
    madeBy:"由 Max777 制作于巴塞罗那",kofi:"🍺 打赏一杯",
  },
  zht:{
    city:"Barcelona · Parc del Fòrum · 2026年6月",
    now:"▶ 緊演緊",next:"⏭ 下一場",remaining:"剩餘",startsIn:"後開始",
    sort:"排序",byTime:"時間",byName:"名稱",catAll:"全部",catMusic:"音樂",catArt:"藝術與社會",catActivity:"活動",
    favs:"💖 我嘅最愛",noFavs:"未有收藏嘅藝人",
    headliner:"HEADLINER",live:"● LIVE",
    mapHint:"雙指縮放 · 撳舞台睇演出",reset:"復位",noShows:"今日暫無演出",mapOfficial:"睇官網高清地圖",
    myEmpty:"💖 收藏藝人後\n喺呢度睇你嘅專屬行程",myTitle:"我嘅行程",conflict:"clash",
    opening:"開幕日",day1:"第一日",day2:"第二日",day3:"第三日",bits:"Bits",free:"免費",
    infoTitle:"實用資訊",
    doorsH:"開門時間",doorsBody:"主場地 Parc del Fòrum 每日約 16:00 開門，演出持續至翌日 05:00–06:00。週三開幕日（6/3）為免費活動，約 17:00 起。",
    transitH:"交通",metroLine:"地鐵 L4（黃線）",metroStop:"El Maresme–Fòrum（步行至 Rambla Prim 約1分鐘）· Selva de Mar（步行至 Carrer de Pujades 約12分鐘）",
    nightbus:"夜巴 N6 / N7 / N28",nightbusDesc:"23:00–06:00，可達市中心（Pl. Catalunya）",
    shuttle:"接駁車（返程）",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · 持通票或單日票可乘 · AccessTicket App 預約（€3/程）\n→ Taulat：週四 00:00–05:00 · 週五 02:00–06:00 · 週六 03:00–06:00\n→ Plataforma Marina：週四至六 01:00–04:00",
    bikeH:"免費單車停車場",bikeDesc:"Plaça de Leonardo da Vinci（Fòrum）· 免費，有限容量\n週三 15:30–00:00 · 週四 14:30–07:00 · 週五六 15:00–07:00 · 週日 13:30–00:00",
    bicing:"Bicing 共享單車",bicingDesc:"場地周邊站點：Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat 等",
    taxi:"的士（返程）",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant（至凌晨 01:00）",
    metroHours:"週一至四 05:00–00:00 · 週五 05:00–02:00 · 週六 24小時不停",tramLine:"電車 T4 線",tramStop:"Fòrum 站 · 週三末班 00:00 · 週四至日通宵不停",daybus:"日間巴士 H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"由市中心沿海濱步行約60分鐘，地中海美景相伴",
    banH:"禁帶物品",
    banItems:["玻璃容器","專業相機／攝錄機（單反等；菲林／卡片機除外）","自拍棍","無人機","寵物（導盲犬除外）"],
    allowItems:["食物（非玻璃容器）","膠樽裝水（≤50cl，無蓋）","自備膠杯（≤40cl）","菲林／卡片／即棄相機","細手袋（A4 大小以內）","雨褸／防曬霜","處方藥（攜帶證明）"],
    banLabel:"禁止攜帶",allowLabel:"允許攜帶",
    weatherH:"天氣預報",
    weatherNote:"六月初嘅巴塞隆拿天氣多變——暴雨過後，氣溫已降至約 21°C。建議攜帶防水外套或雨披，同埋一件額外外套應對凌晨場。場地內有防曬霜取用站。出門前記得查睇天氣預報。",
    tipsH:"實用小貼士",
    tips:["AccessTicket 手帶需喺入口激活，請留出排隊時間","現金充值點分布喺場地各處（僅 AccessTicket 消費）","免費飲水站全場分布，自備空樽可慳開支","Nobody Is Normal 安全站提供緊急援助","免費水點高峰時段排隊較長。建議換舞台時順手補滿水樽，唔好等口渴先去"],
    emergH:"緊急援助",
    emergItems:["緊急電話：112","安全站：主入口及各主舞台兩側均設有援助點","與同伴走失時：喺主舞台正前方集合"],
    ticketsH:"門票",
    ticketSalesBody:"官方購票渠道：Fever App（iOS/Android）同 AccessTicket（支援分期付款）。門票可喺 AccessTicket 中轉讓（未使用且未關聯活動預約）。唔需要打印——直接用 AccessTicket App 掃碼驗票。",
    ticketTypesBody:"Parc del Fòrum 僅提供三日通票同單日票，冇單場演出票。",
    ticketQRBody:"二維碼僅允許入場一次，請妥善保管。唔好截圖俾他人，唔好喺社交媒體發布。",
    minorsH:"未成年人",
    minor12:"12歲及以下（含）：免票，需喺 Fever 領取免費票，由父母或法定監護人陪同（攜帶證件及本人門票）。",
    minor1315:"13–15歲：需購買未成年人票，必須由父母或法定監護人陪同（不含兄弟姐妹或其他親屬）。",
    minor1617:"16–17歲：購買青少年票後可獨立入場（無需陪同）。部分場館演出需年滿18歲。",
    accessH:"無障礙服務（PRM）",
    accessBody:"行動不便及有特殊需求人士可經快速通道入場（可攜帶一名陪伴者）。各主要舞台均設專屬觀看區及無障礙廁所。",
    accessEmail:"accessibility@primaverasound.com",
    payH:"場內付款方式",
    payBody:"支援信用／借記卡（Visa 及 Mastercard；不接受美國運通）同 AccessTicket 錢包。",
    lostH:"失物招領",
    lostBody:"節日期間失物統一送至外部資訊點，可就近前往或填寫失物表格。節日結束後未認領物品移交至 Guàrdia Urbana de Poblenou（Carrer d'Espronceda, 148）。",
    faqH:"官方常見問題",faqLink:"睇完整官方 FAQ",
    navHome:"主頁",navSchedule:"演出表",navMap:"地圖",navFavs:"最愛",navInfo:"實用資訊",navTheme:"主題",navLang:"語言",
    showPast:"場已完",hidePast:"隱藏已完",more:"更多",collapse:"收起",
    disclaimer:"本站為樂迷自製嘅非官方指南，與 Primavera Sound S.L. 無任何關聯。<br>所有商標歸各自所有者所有。<br>演出資訊僅供參考，請以<a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">官方網站</a>為準。<br>反饋或糾錯請聯絡：",
    madeBy:"由 Max777 製作於巴塞隆拿",kofi:"🍺 打賞一杯",
  },
  es:{
    city:"Barcelona · Parc del Fòrum · Junio 2026",
    now:"▶ EN ESCENA",next:"⏭ PRÓXIMO",remaining:"restante",startsIn:"para empezar",
    sort:"Orden",byTime:"Hora",byName:"Nombre",catAll:"Todo",catMusic:"Música",catArt:"Arte y activismo",catActivity:"Actividades",
    favs:"💖 Mis favoritos",noFavs:"Aún no tienes favoritos",
    headliner:"HEADLINER",live:"● EN DIRECTO",
    mapHint:"Pellizca para zoom · Toca el escenario",reset:"Reset",noShows:"Sin conciertos hoy",mapOfficial:"Ver mapa oficial en alta resolución",
    myEmpty:"💖 Guarda artistas\npara ver tu itinerario personal",myTitle:"Mi agenda",conflict:"Conflicto",
    opening:"Apertura",day1:"Día 1",day2:"Día 2",day3:"Día 3",bits:"Bits",free:"Gratis",
    infoTitle:"Info práctica",
    doorsH:"Horarios de apertura",doorsBody:"El Parc del Fòrum abre cada día sobre las 16:00, los conciertos siguen hasta las 05:00–06:00. El miércoles de apertura (3/6) es gratuito desde las ~17:00.",
    transitH:"Transporte",metroLine:"Metro L4 (línea amarilla)",metroStop:"El Maresme–Fòrum (→ Rambla Prim, 1 min a pie) · Selva de Mar (→ Carrer de Pujades, 12 min a pie)",
    nightbus:"Autobús nocturno N6 / N7 / N28",nightbusDesc:"23:00–06:00 al centro (Pl. Catalunya)",
    shuttle:"Lanzaderas (regreso)",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · Poseedores de abono y entrada de día · Reserva en AccessTicket App (€3/trayecto)\n→ Taulat: Jue 00:00–05:00 · Vie 02:00–06:00 · Sáb 03:00–06:00\n→ Plataforma Marina: Jue–Sáb 01:00–04:00",
    bikeH:"Aparcamiento de bicicletas",bikeDesc:"Plaça de Leonardo da Vinci (Fòrum) · Gratis, aforo limitado\nMié 15:30–00:00 · Jue 14:30–07:00 · Vie–Sáb 15:00–07:00 · Dom 13:30–00:00",
    bicing:"Bicing (bici compartida)",bicingDesc:"Estaciones próximas: Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat",
    taxi:"Taxi (regreso)",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant (hasta las 01:00)",
    metroHours:"L–J 05:00–00:00 · V 05:00–02:00 · S servicio continuo 24h",tramLine:"Tranvía T4",tramStop:"Fòrum · Miércoles hasta 00:00 · Jueves–Domingo servicio continuo",daybus:"Autobús diurno H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"Paseo de ~60 min desde el centro por el Passeig Marítim con vistas al Mediterráneo",
    banH:"Objetos prohibidos",
    banItems:["Recipientes de vidrio","Cámara profesional/de vídeo (DSLR; no las compactas/analógicas)","Palos selfie","Drones","Mascotas (excepto perros guía)"],
    allowItems:["Comida (no en envases de vidrio)","Agua en botella de plástico ≤50cl sin tapón","Vaso de plástico propio ≤40cl","Cámara analógica, compacta o desechable","Bolso pequeño (tamaño A4)","Chubasquero / protector solar","Medicación con receta (con justificante)"],
    banLabel:"Prohibido",allowLabel:"Permitido",
    weatherH:"Previsión meteorológica",
    weatherNote:"Los primeros días de junio en Barcelona pueden ser impredecibles — tras la tormenta, las temperaturas han bajado a unos 21°C. Lleva un chubasquero o poncho y una capa extra para los conciertos de madrugada. Hay estaciones de protector solar en el recinto. Consulta la previsión antes de salir de casa.",
    tipsH:"Consejos prácticos",
    tips:["La pulsera AccessTicket debe activarse en la entrada; deja tiempo para la cola","Puntos de recarga de efectivo distribuidos por el recinto (solo pago con AccessTicket)","Fuentes de agua gratuitas en todo el recinto","El punto Nobody Is Normal ofrece asistencia de emergencia","Las fuentes de agua hacen cola en horas punta. Rellena la botella cuando cambies de escenario, no cuando tengas sed"],
    emergH:"Emergencias / Punto de ayuda",
    emergItems:["Teléfono de emergencias: 112","Punto de seguridad en la entrada principal y a los laterales de los escenarios principales","Si te pierdes del grupo: punto de encuentro delante del escenario principal"],
    ticketsH:"Entradas",
    ticketSalesBody:"Venta oficial: Fever (App Store/Google Play) y AccessTicket (pago a plazos). Las entradas son transferibles en AccessTicket si no han sido usadas ni vinculadas a actividades. No es necesario imprimir: se validan desde la app AccessTicket.",
    ticketTypesBody:"Solo hay pase de festival (3 días) o entradas de día. No hay entradas por concierto.",
    ticketQRBody:"El código QR solo permite un acceso. No compartas capturas de pantalla ni lo publiques en redes sociales.",
    minorsH:"Menores",
    minor12:"Hasta 12 años (incluido): entrada gratuita con ticket de Fever, acompañados por padre/madre o tutor legal (con documentación y entrada propia).",
    minor1315:"13–15 años: entrada de menores obligatoria. Deben ir acompañados por padre/madre o tutor legal (no hermanos ni otros familiares).",
    minor1617:"16–17 años: con entrada teen pueden entrar sin acompañante. Algunos conciertos en salas requieren 18+.",
    accessH:"Accesibilidad (PRM)",
    accessBody:"Las personas con movilidad reducida pueden acceder por carril rápido con un acompañante. Hay zonas reservadas en casi todos los escenarios y baños adaptados en todo el recinto.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Métodos de pago",
    payBody:"Tarjeta de crédito/débito (Visa y Mastercard; no se acepta American Express) y monedero AccessTicket.",
    lostH:"Objetos perdidos",
    lostBody:"Los objetos encontrados se llevan al punto de información exterior. Ve a cualquier punto de info o rellena el formulario. Tras el festival, los no reclamados van a la Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"FAQ oficial",faqLink:"Ver preguntas frecuentes oficiales",
    navHome:"Inicio",navSchedule:"Horario",navMap:"Mapa",navFavs:"Guardados",navInfo:"Info",navTheme:"Tema",navLang:"Idioma",
    showPast:"terminados",hidePast:"Ocultar pasados",more:"más",collapse:"colapsar",
    disclaimer:"Sitio no oficial creado por fans.<br>Sin afiliación con Primavera Sound S.L.<br>Todas las marcas pertenecen a sus respectivos propietarios.<br>Información orientativa; consulta la <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">web oficial</a>.<br>Sugerencias o correcciones:",
    madeBy:"Hecho por Max777 en Barcelona",kofi:"🍺 fondo de cervezas",
  },
  ca:{
    city:"Barcelona · Parc del Fòrum · Juny 2026",
    now:"▶ EN DIRECTE",next:"⏭ PRÒXIM",remaining:"restant",startsIn:"per començar",
    sort:"Ordre",byTime:"Hora",byName:"Nom",catAll:"Tot",catMusic:"Música",catArt:"Art i activisme",catActivity:"Activitats",
    favs:"💖 Els meus favorits",noFavs:"Encara no tens favorits",
    headliner:"HEADLINER",live:"● EN DIRECTE",
    mapHint:"Pessiga per fer zoom · Toca l'escenari",reset:"Reinicia",noShows:"Avui no hi ha concerts",mapOfficial:"Veure el mapa oficial en alta resolució",
    myEmpty:"💖 Desa artistes\nper veure el teu itinerari personal aquí",myTitle:"El meu itinerari",conflict:"Solapament",
    opening:"Obertura",day1:"Dia 1",day2:"Dia 2",day3:"Dia 3",bits:"Bits",free:"Gratis",
    infoTitle:"Informació pràctica",
    doorsH:"Horaris d'obertura",doorsBody:"El Parc del Fòrum obre cada dia cap a les 16:00, els concerts continuen fins a les 05:00–06:00. El dimecres d'obertura (3/6) és gratuït des de les ~17:00.",
    transitH:"Com arribar-hi",metroLine:"Metro L4 (línia groga)",metroStop:"El Maresme–Fòrum (→ Rambla Prim, 1 min a peu) · Selva de Mar (→ Carrer de Pujades, 12 min a peu)",
    nightbus:"Autobús nocturn N6 / N7 / N28",nightbusDesc:"23:00–06:00 al centre (Pl. Catalunya)",
    shuttle:"Llançadores (tornada)",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · Posseïdors d'abonament i entrada de dia · Reserva a AccessTicket App (€3/trajecte)\n→ Taulat: Dj 00:00–05:00 · Dv 02:00–06:00 · Ds 03:00–06:00\n→ Plataforma Marina: Dj–Ds 01:00–04:00",
    bikeH:"Aparcament de bicicletes",bikeDesc:"Plaça de Leonardo da Vinci (Fòrum) · Gratuït, aforament limitat\nDc 15:30–00:00 · Dj 14:30–07:00 · Dv–Ds 15:00–07:00 · Dg 13:30–00:00",
    bicing:"Bicing (bici compartida)",bicingDesc:"Estacions properes: Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat",
    taxi:"Taxi (tornada)",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant (fins a les 01:00)",
    metroHours:"Dl–Dj 05:00–00:00 · Dv 05:00–02:00 · Ds servei continu 24h",tramLine:"Tramvia T4",tramStop:"Fòrum · Dimecres fins a 00:00 · Dijous–Diumenge servei continu",daybus:"Autobusos diürns H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"~60 min a peu des del centre per la rambla del mar amb vistes al Mediterrani",
    banH:"Objectes prohibits",
    banItems:["Recipients de vidre","Càmera professional/de vídeo (DSLR; compactes i analògiques OK)","Pals selfie","Drons","Mascotes (excepte gossos d'assistència)"],
    allowItems:["Menjar (no en recipients de vidre)","Aigua en ampolla de plàstic ≤ 50 cl (sense tap a l'entrada)","Got de plàstic propi ≤ 40 cl","Càmera analògica, compacta o d'un sol ús","Bossa petita (fins a mida A4)","Impermeable / protector solar","Medicació amb recepta (amb documentació)"],
    banLabel:"No permès",allowLabel:"Permès",
    weatherH:"Previsió meteorològica",
    weatherNote:"Els primers dies de juny a Barcelona poden ser imprevisibles — després de la tempesta, les temperatures han baixat fins a uns 21°C. Porta un impermeable o ponxo i una capa extra per als concerts de matinada. Hi ha estacions de protector solar al recinte. Consulta la previsió abans de sortir de casa.",
    tipsH:"Consells pràctics",
    tips:["La polsera AccessTicket s'ha d'activar a l'entrada — deixa temps per fer cua","Punts de recàrrega en efectiu distribuïts pel recinte (pagament AccessTicket)","Fonts d'aigua gratuïtes per tot el recinte","El punt Nobody Is Normal ofereix assistència d'emergència","Tot i que hi ha fonts d'aigua, fan llargues cues durant les hores punta. Omple l'ampolla quan canvies d'escenari, no quan tinguis set"],
    emergH:"Emergències / Punt d'ajuda",
    emergItems:["Telèfon d'emergències: 112","Punt de seguretat: a l'entrada principal i als laterals dels escenaris principals","Si et perds del grup: punt de trobada davant l'escenari principal"],
    ticketsH:"Entrades",
    ticketSalesBody:"Venda oficial: Fever (iOS/Android) i AccessTicket (pagament a terminis). Les entrades es poden cedir a AccessTicket si no han estat usades ni vinculades a activitats. No cal imprimir — es validen des de l'app AccessTicket.",
    ticketTypesBody:"Només hi ha abonaments de festival (3 dies) i entrades de dia. No hi ha entrades per concert.",
    ticketQRBody:"El codi QR només funciona un cop. No comparteixis captures de pantalla ni el publiquis a les xarxes socials.",
    minorsH:"Menors",
    minor12:"Fins a 12 anys (inclosos): entrada gratuïta amb tiquet de Fever, acompanyats per pare/mare o tutor legal (amb documentació i entrada pròpia).",
    minor1315:"13–15 anys: entrada de menors obligatòria. Han d'anar acompanyats per pare/mare o tutor legal (no germans ni altres familiars).",
    minor1617:"16–17 anys: amb entrada teen poden entrar sense acompanyant. Alguns espectacles en sala requereixen 18+.",
    accessH:"Accessibilitat (PMR)",
    accessBody:"Les persones amb mobilitat reduïda poden accedir per carril ràpid amb un acompanyant. Hi ha zones reservades a gairebé tots els escenaris i lavabos adaptats arreu del recinte.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Mètodes de pagament",
    payBody:"Targeta de crèdit/dèbit (Visa i Mastercard; no s'accepta American Express) i moneder AccessTicket.",
    lostH:"Objectes perduts",
    lostBody:"Els objectes trobats es porten al punt d'informació exterior. Ves a qualsevol punt d'informació o omple el formulari. Després del festival, els no reclamats van a la Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"Preguntes freqüents oficials",faqLink:"Veure les preguntes freqüents oficials",
    navHome:"Inici",navSchedule:"Horari",navMap:"Mapa",navFavs:"Preferits",navInfo:"Info",navTheme:"Tema",navLang:"Idioma",
    showPast:"acabats",hidePast:"Amaga els acabats",more:"més",collapse:"replegar",
    disclaimer:"Guia no oficial creada per fans.<br>Sense afiliació amb Primavera Sound S.L.<br>Totes les marques pertanyen als seus respectius propietaris.<br>Informació orientativa; consulta el <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">lloc web oficial</a>.<br>Comentaris o correccions:",
    madeBy:"Fet per Max777 a Barcelona",kofi:"🍺 fons de cerveses",
  },
  pt:{
    city:"Barcelona · Parc del Fòrum · Junho 2026",
    now:"▶ EM CENA",next:"⏭ A SEGUIR",remaining:"restante",startsIn:"para começar",
    sort:"Ordem",byTime:"Hora",byName:"Nome",catAll:"Tudo",catMusic:"Música",catArt:"Arte e ativismo",catActivity:"Atividades",
    favs:"💖 Os meus favoritos",noFavs:"Ainda não tens favoritos",
    headliner:"HEADLINER",live:"● AO VIVO",
    mapHint:"Belisca para zoom · Toca no palco",reset:"Repor",noShows:"Sem concertos hoje",mapOfficial:"Ver mapa oficial em alta resolução",
    myEmpty:"💖 Guarda artistas\npara ver o teu itinerário pessoal",myTitle:"O meu itinerário",conflict:"Conflito",
    opening:"Abertura",day1:"Dia 1",day2:"Dia 2",day3:"Dia 3",bits:"Bits",free:"Grátis",
    infoTitle:"Info prática",
    doorsH:"Horários de abertura",doorsBody:"O Parc del Fòrum abre todos os dias por volta das 16:00, com concertos até às 05:00–06:00. A quarta-feira de abertura (3/6) é gratuita a partir das ~17:00.",
    transitH:"Como chegar",metroLine:"Metro L4 (linha amarela)",metroStop:"El Maresme–Fòrum (→ Rambla Prim, 1 min a pé) · Selva de Mar (→ Carrer de Pujades, 12 min a pé)",
    nightbus:"Autocarros noturnos N6 / N7 / N28",nightbusDesc:"23:00–06:00 para o centro (Pl. Catalunya)",
    shuttle:"Autocarros de ligação (regresso)",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · Detentores de passe e bilhete de dia · Reserva na app AccessTicket (€3/viagem)\n→ Taulat: Qui 00:00–05:00 · Sex 02:00–06:00 · Sáb 03:00–06:00\n→ Plataforma Marina: Qui–Sáb 01:00–04:00",
    bikeH:"Parque de bicicletas gratuito",bikeDesc:"Plaça de Leonardo da Vinci (Fòrum) · Gratuito, capacidade limitada\nQua 15:30–00:00 · Qui 14:30–07:00 · Sex–Sáb 15:00–07:00 · Dom 13:30–00:00",
    bicing:"Bicing (bicicletas partilhadas)",bicingDesc:"Estações próximas: Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat",
    taxi:"Táxi (regresso)",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant (até à 01:00)",
    metroHours:"Seg–Qui 05:00–00:00 · Sex 05:00–02:00 · Sáb serviço contínuo 24h",tramLine:"Elétrico T4",tramStop:"Fòrum · Quarta-feira até às 00:00 · Quinta a Domingo serviço contínuo",daybus:"Autocarros diurnos H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"~60 min a pé do centro pela Promenade Marítima com vistas para o Mediterrâneo",
    banH:"Objetos proibidos",
    banItems:["Recipientes de vidro","Câmeras profissionais/de vídeo (DSLR; compactas e analógicas OK)","Pau de selfie","Drones","Animais de estimação (exceto cães-guia)"],
    allowItems:["Comida (não em recipientes de vidro)","Água em garrafa de plástico ≤50cl (sem tampa na entrada)","Copo de plástico próprio ≤40cl","Câmera analógica, compacta ou descartável","Mala pequena (até tamanho A4)","Impermeável / protetor solar","Medicação com receita (com documentação)"],
    banLabel:"Proibido",allowLabel:"Permitido",
    weatherH:"Previsão meteorológica",
    weatherNote:"Os primeiros dias de junho em Barcelona podem ser imprevisíveis — após a tempestade, as temperaturas baixaram para cerca de 21°C. Traz um impermeável ou poncho e uma camada extra para os concertos de madrugada. Há estações de protetor solar no recinto. Consulta a previsão antes de sair de casa.",
    tipsH:"Dicas práticas",
    tips:["A pulseira AccessTicket tem de ser ativada na entrada — deixa tempo para a fila","Pontos de recarregamento de saldo distribuídos pelo recinto (apenas pagamento AccessTicket)","Fontes de água gratuitas em todo o recinto","O ponto Nobody Is Normal oferece assistência de emergência","As fontes de água fazem filas longas nas horas de ponta. Enche a garrafa quando mudas de palco, não quando já tens sede"],
    emergH:"Emergências / Ponto de ajuda",
    emergItems:["Número de emergência: 112","Pontos de segurança na entrada principal e em ambos os lados dos palcos principais","Se te separas do grupo: ponto de encontro em frente ao palco principal"],
    ticketsH:"Bilhetes",
    ticketSalesBody:"Venda oficial: Fever (iOS/Android) e AccessTicket (prestações disponíveis). Os bilhetes são transferíveis no AccessTicket se não foram usados nem associados a atividades. Não é necessário imprimir — validados pela app AccessTicket.",
    ticketTypesBody:"Apenas passes de festival (3 dias) e bilhetes de dia disponíveis. Não há bilhetes por concerto.",
    ticketQRBody:"O código QR apenas funciona uma vez. Não partilhes capturas de ecrã nem o publiques nas redes sociais.",
    minorsH:"Menores",
    minor12:"Até 12 anos (inclusive): entrada gratuita com bilhete do Fever, acompanhados por pai/mãe ou tutor legal (com documentação e bilhete próprio).",
    minor1315:"13–15 anos: bilhete de menores obrigatório. Devem ser acompanhados por pai/mãe ou tutor legal (não irmãos ou outros familiares).",
    minor1617:"16–17 anos: com bilhete teen podem entrar sem acompanhante. Alguns espetáculos em sala requerem 18+.",
    accessH:"Acessibilidade (PRM)",
    accessBody:"Pessoas com mobilidade reduzida podem aceder por via rápida com um acompanhante. Há zonas reservadas em quase todos os palcos e casas de banho adaptadas em todo o recinto.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Métodos de pagamento",
    payBody:"Cartão de crédito/débito (Visa e Mastercard; Amex não aceite) e carteira AccessTicket.",
    lostH:"Perdidos e achados",
    lostBody:"Os objetos encontrados são levados ao ponto de informação exterior. Vai a qualquer ponto de informação ou preenche o formulário. Após o festival, os objetos não reclamados vão para a Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"FAQ oficial",faqLink:"Ver as perguntas frequentes oficiais",
    navHome:"Início",navSchedule:"Horário",navMap:"Mapa",navFavs:"Guardados",navInfo:"Info",navTheme:"Tema",navLang:"Idioma",
    showPast:"terminados",hidePast:"Ocultar terminados",more:"mais",collapse:"recolher",
    disclaimer:"Guia não oficial feito por fãs.<br>Sem afiliação com a Primavera Sound S.L.<br>Todas as marcas pertencem aos seus respetivos proprietários.<br>Informação a título indicativo; consulta o <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">site oficial</a>.<br>Sugestões ou correções:",
    madeBy:"Feito por Max777 em Barcelona",kofi:"🍺 fundo de cervejas",
  },
  en:{
    city:"Barcelona · Parc del Fòrum · June 2026",
    now:"▶ NOW PLAYING",next:"⏭ UP NEXT",remaining:"left",startsIn:"to start",
    sort:"Sort",byTime:"Time",byName:"Name",catAll:"All",catMusic:"Music",catArt:"Art & Activism",catActivity:"Activities",
    favs:"💖 My Favourites",noFavs:"No saved artists yet",
    headliner:"HEADLINER",live:"● LIVE",
    mapHint:"Pinch to zoom · Tap stage to see shows",reset:"Reset",noShows:"No shows today",mapOfficial:"View official hi-res map",
    myEmpty:"💖 Save artists\nto see your personal lineup here",myTitle:"My lineup",conflict:"Clash",
    opening:"Opening",day1:"Day 1",day2:"Day 2",day3:"Day 3",bits:"Bits",free:"Free",
    infoTitle:"Practical Info",
    doorsH:"Opening hours",doorsBody:"Parc del Fòrum opens daily around 16:00, with sets running until 05:00–06:00. Wednesday opening day (3 June) is free from ~17:00.",
    transitH:"Getting there",metroLine:"Metro L4 (Yellow line)",metroStop:"El Maresme–Fòrum (→ Rambla Prim, 1 min walk) · Selva de Mar (→ Carrer de Pujades, 12 min walk)",
    nightbus:"Night buses N6 / N7 / N28",nightbusDesc:"23:00–06:00 to city centre (Pl. Catalunya)",
    shuttle:"Shuttle buses (return)",shuttleDesc:"Parc del Fòrum → Plaça Catalunya · Full festival & day ticket holders · Book via AccessTicket App (€3/trip)\n→ Taulat: Thu 00:00–05:00 · Fri 02:00–06:00 · Sat 03:00–06:00\n→ Plataforma Marina: Thu–Sat 01:00–04:00",
    bikeH:"Free bike parking",bikeDesc:"Plaça de Leonardo da Vinci (Fòrum) · Free, limited capacity\nWed 15:30–00:00 · Thu 14:30–07:00 · Fri–Sat 15:00–07:00 · Sun 13:30–00:00",
    bicing:"Bicing (shared bikes)",bicingDesc:"Nearby stations: Avda. Eduard Maristany 1 · Rambla Prim 19 · Pssg. Garcia Fària 85 · Selva de Mar/Pssg. Taulat",
    taxi:"Taxi (return)",taxiDesc:"C/ Josep Pla 2, 4, 6 · Pssg. Taulat / Pl. de Llevant (until 01:00)",
    metroHours:"Mon–Thu 05:00–00:00 · Fri 05:00–02:00 · Sat 24h non-stop",tramLine:"Tram T4",tramStop:"Fòrum · Wed until 00:00 · Thu–Sun non-stop service",daybus:"Day buses H16 / 7 / 136 / V33 / V31 / V29 / H14 / B20 / B23",daybusDesc:"06:30–23:15",walkDesc:"~60 min walk from city centre along the beach promenade with sea views",
    banH:"Prohibited items",
    banItems:["Glass containers","Professional/video cameras (DSLR; compact & analogue OK)","Selfie sticks","Drones","Pets (except assistance dogs)"],
    allowItems:["Food (not in glass containers)","Water in plastic bottle ≤50cl (cap removed at gate)","Your own plastic cup ≤40cl","Analogue, compact or disposable cameras","Small bag (up to A4 size)","Raincoat / sunscreen","Prescription medication (with documentation)"],
    banLabel:"Not allowed",allowLabel:"Allowed",
    weatherH:"Weather forecast",
    weatherNote:"Early June in Barcelona can be unpredictable — after the storm, temperatures have dropped to around 21°C. Bring a waterproof jacket or poncho and an extra layer for late-night sets. Sunscreen stations are available on-site. Check the forecast before you leave home.",
    tipsH:"Practical tips",
    tips:["Your AccessTicket wristband must be activated at the entrance — allow time to queue","Cash reload points are scattered around the venue (AccessTicket payment only)","Free water points throughout the venue","Nobody Is Normal safe space provides emergency assistance","Free water points get long queues at peak hours. Top up your bottle when moving between stages, not when you're already thirsty"],
    emergH:"Emergency / Help point",
    emergItems:["Emergency number: 112","Safety points at the main entrance and on both sides of the main stages","If separated from your group: meeting point in front of the main stage"],
    ticketsH:"Tickets",
    ticketSalesBody:"Official sales: Fever (iOS/Android) and AccessTicket (instalments). Tickets are transferable in AccessTicket if unused and not linked to any activity. No printing needed — validated via the AccessTicket app.",
    ticketTypesBody:"Only full festival passes (3 days) and single day tickets available. No single-concert tickets.",
    ticketQRBody:"The QR code only works once. Do not share screenshots or post it on social media.",
    minorsH:"Minors",
    minor12:"Up to 12 (inclusive): free entry with a Fever ticket, accompanied by a parent or legal guardian (with ID and their own ticket).",
    minor1315:"Ages 13–15: minors' ticket required. Must be accompanied by a parent or legal guardian — siblings or other relatives not permitted.",
    minor1617:"Ages 16–17: teen ticket, may enter unaccompanied. Some venue shows require 18+.",
    accessH:"Accessibility (PRM)",
    accessBody:"People with reduced mobility can use a fast-track entrance with one companion. Reserved viewing areas at most stages and adapted restrooms throughout the venue.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Payment methods",
    payBody:"Credit/debit cards (Visa & Mastercard; Amex not accepted) and the AccessTicket wallet.",
    lostH:"Lost & found",
    lostBody:"Found items are taken to the external info point. Visit any info point or fill in the lost & found form. After the festival, unclaimed items go to Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"Official FAQ",faqLink:"View the full official FAQ",
    navHome:"Home",navSchedule:"Schedule",navMap:"Map",navFavs:"Saved",navInfo:"Info",navTheme:"Theme",navLang:"Language",
    showPast:"ended",hidePast:"Hide ended",more:"more",collapse:"collapse",
    disclaimer:"Unofficial fan-made guide.<br>Not affiliated with Primavera Sound S.L.<br>All trademarks belong to their respective owners.<br>Information for reference only; check the <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">official site</a>.<br>Feedback or corrections:",
    madeBy:"Made by Max777 in Barcelona",kofi:"🍺 beer fund",
  }
};

var curLang=localStorage.getItem("ps26_lang")||(function(){
  var ls=navigator.languages||[navigator.language||"en"];
  for(var i=0;i<ls.length;i++){var l=ls[i].toLowerCase();
    if(l==="ca"||l.startsWith("ca-"))return"ca";
    if(l==="yue"||l.startsWith("yue-"))return"zht";
    if(l==="zh-hk"||l==="zh-tw"||l==="zh-mo"||l==="zh-hant"||l.startsWith("zh-hant-"))return"zht";
    if(l==="zh"||l.startsWith("zh-"))return"zh";
    if(l==="es"||l.startsWith("es-"))return"es";
    if(l==="pt"||l.startsWith("pt-"))return"pt";
  }
  return"en";
})();
function t(k){return (LANGS[curLang]&&LANGS[curLang][k])||LANGS.zh[k]||k;}
function setLang(l){
  curLang=l;localStorage.setItem("ps26_lang",l);
  if(typeof vaTrack==='function')vaTrack('switch_language',{lang:l});
  applyLang();
  renderDayTabs();
  render();
  updateNowPlaying();
  if(typeof updateThemeToggleUI==='function')updateThemeToggleUI();
}
function applyLang(){
  document.querySelectorAll(".lang-btn,.home-lang-btn").forEach(function(b){b.classList.toggle("on",b.dataset.lang===curLang);});
  var _lc=document.getElementById("lbl-city");if(_lc)_lc.textContent=t("city");
  var _lm=document.getElementById("lbl-mapHint");if(_lm)_lm.textContent=t("mapHint");
  var _lr=document.getElementById("lbl-reset");if(_lr)_lr.textContent=t("reset");
  var _lf=document.getElementById("lbl-favs");if(_lf)_lf.textContent=t("favs");
  var _ls=document.getElementById("lbl-sort");if(_ls)_ls.textContent=t("sort");
  document.querySelectorAll("[data-i]").forEach(function(el){el.textContent=t(el.dataset.i);});
  var footer=document.getElementById("app-footer");
  if(footer)footer.innerHTML=t("disclaimer")+' <a class="footer-mail" href="mailto:maxx7770101@gmail.com">maxx7770101@gmail.com</a>';
  if(curView==="info")renderInfo();
}