// ── I18N ──
var LANGS={
  zh:{
    city:"Barcelona · Parc del Fòrum · Junio 2026",
    now:"▶ 正在演出",next:"⏭ 下一场",remaining:"剩余",startsIn:"后开始",
    sort:"排序",byTime:"时间",byName:"名称",
    favs:"💖 我的收藏",noFavs:"还没有收藏的艺人",
    headliner:"HEADLINER",live:"● LIVE",
    mapHint:"双指缩放 · 点击舞台查看演出",reset:"复位",noShows:"今天暂无演出",mapOfficial:"点击查看官网高清地图",
    myEmpty:"💖 收藏艺人后\n在这里查看你的专属行程",myTitle:"我的行程",conflict:"时间冲突",
    opening:"开幕日",day1:"第一天",day2:"第二天",day3:"第三天",bits:"Bits",free:"免费",
    infoTitle:"实用信息",
    doorsH:"开门时间",doorsBody:"主场地 Parc del Fòrum 每天约 16:00 开门，演出持续至次日 05:00–06:00。周三开幕日（6/3）为免费活动，约 17:00 起。",
    transitH:"交通",metroLine:"地铁 L4（黄线）",metroStop:"El Maresme | Fòrum 站",
    nightbus:"夜巴士 N6",nightbusDesc:"凌晨收班后运营，约 15 分钟一班，可达市中心（Pl. Catalunya）",
    bikeDesc:"场地内有免费单车停放区",metroHours:"周一至四 05:00–00:00 · 周五 05:00–02:00 · 周六 24小时连续运营",tramLine:"电车 T4 线",tramStop:"Fòrum 站 · 节日期间增加班次",daybus:"日间公交 H16 / H14 / 143 / 7 / 36",daybusDesc:"从市中心各区直达，运营时间 06:30–23:15",shuttle:"官方摆渡车",shuttleDesc:"午夜至早晨约€2，Passeig Taulat → Plaça Catalunya，AccessTicket App 可预约",walkDesc:"从市中心沿海滨步行约60分钟，地中海美景相伴",
    banH:"禁带物品",
    banItems:["玻璃容器","专业相机/摄像机（单反等；胶片/卡片机除外）","自拍杆","无人机","宠物（导盲犬除外）"],
    allowItems:["食物（非玻璃容器）","塑料瓶装水（≤50cl，无盖）","自带塑料杯（≤40cl）","胶片/卡片/一次性相机","小型手提包（A4 大小以内）","雨衣/防晒霜","处方药（携带证明）"],
    banLabel:"禁止携带",allowLabel:"允许携带",
    weatherH:"天气预报",
    weatherNote:"六月初巴塞罗那通常晴朗，日间 25–30°C，夜间 18–22°C。建议携带防晒霜和轻便外套（凌晨场较凉）。",
    tipsH:"实用小贴士",
    tips:["AccessTicket 手环需在入口激活，请留出排队时间","现金充值点分布在场地各处（仅 AccessTicket 消费）","免费饮水站全场分布，自带空瓶可节省开支","Nobody Is Normal 安全站提供紧急援助","免费水点高峰时段排队较长。建议换舞台时顺手补满水瓶，不要等口渴了再去"],
    emergH:"紧急援助",
    emergItems:["紧急电话：112","安全站：主入口及各主舞台两侧均设有援助点","与同伴走散时：在主舞台正前方集合"],
    ticketsH:"门票",
    ticketSalesBody:"官方购票渠道：Fever App（iOS/Android）和 AccessTicket（支持分期付款）。门票可在 AccessTicket 中转让（未使用且未关联活动预约）。无需打印——直接用 AccessTicket App 扫码验票。",
    ticketTypesBody:"Parc del Fòrum 仅提供三日通票和单日票，无单场演出票。",
    ticketQRBody:"二维码仅允许入场一次，请妥善保管。不要截图发给他人，不要在社交媒体发布。",
    minorsH:"未成年人",
    minor12:"12岁及以下（含）：免票，需在 Fever 领取免费票，由父母或法定监护人陪同（携带证件及本人门票）。",
    minor1315:"13–15岁：需购买未成年人票，必须由父母或法定监护人陪同（不含兄弟姐妹或其他亲属）。",
    minor1617:"16–17岁：购买青少年票后可独立入场（无需陪同）。部分场馆演出需年满18岁。",
    accessH:"无障碍服务（PRM）",
    accessBody:"行动不便及有特殊需求人士可通过快速通道入场（可携带一名陪伴者）。各主要舞台均设专属观看区及无障碍卫生间。",
    accessEmail:"accessibility@primaverasound.com",
    payH:"场内支付方式",
    payBody:"支持信用/借记卡（Visa 及 Mastercard；不接受美国运通）和 AccessTicket 钱包。",
    lostH:"失物招领",
    lostBody:"节日期间失物统一送至外部信息点，可就近前往或填写失物表格。节日结束后未认领物品移交至 Guàrdia Urbana de Poblenou（Carrer d'Espronceda, 148）。",
    faqH:"官方常见问题",faqLink:"查看完整官方 FAQ",
    navHome:"首页",navSchedule:"演出表",navMap:"地图",navFavs:"收藏",navInfo:"实用信息",navTheme:"主题",navLang:"语言",
    showPast:"场已结束",hidePast:"隐藏已结束",more:"更多",collapse:"收起",
    disclaimer:"本站为乐迷自制的非官方指南，与 Primavera Sound S.L. 无任何关联。<br>所有商标归各自所有者所有。<br>演出信息仅供参考，请以<a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">官方网站</a>为准。<br>反馈或纠错请联系：",
  },
  es:{
    city:"Barcelona · Parc del Fòrum · Junio 2026",
    now:"▶ EN ESCENA",next:"⏭ PRÓXIMO",remaining:"restante",startsIn:"para empezar",
    sort:"Orden",byTime:"Hora",byName:"Nombre",
    favs:"💖 Mis favoritos",noFavs:"Aún no tienes favoritos",
    headliner:"HEADLINER",live:"● EN DIRECTO",
    mapHint:"Pellizca para zoom · Toca el escenario",reset:"Reset",noShows:"Sin conciertos hoy",mapOfficial:"Ver mapa oficial en alta resolución",
    myEmpty:"💖 Guarda artistas\npara ver tu itinerario personal",myTitle:"Mi agenda",conflict:"Conflicto",
    opening:"Apertura",day1:"Día 1",day2:"Día 2",day3:"Día 3",bits:"Bits",free:"Gratis",
    infoTitle:"Info práctica",
    doorsH:"Horarios de apertura",doorsBody:"El Parc del Fòrum abre cada día sobre las 16:00, los conciertos siguen hasta las 05:00–06:00. El miércoles de apertura (3/6) es gratuito desde las ~17:00.",
    transitH:"Transporte",metroLine:"Metro L4 (línea amarilla)",metroStop:"Parada El Maresme | Fòrum",
    nightbus:"Autobús nocturno N6",nightbusDesc:"Servicio nocturno tras el cierre del metro, cada ~15 min hasta el centro (Pl. Catalunya)",
    bikeDesc:"Aparcamiento de bicicletas gratuito en el recinto",metroHours:"L-J 05:00–00:00 · V 05:00–02:00 · S servicio continuo 24h",tramLine:"Tranvía T4",tramStop:"Parada Fòrum · Servicio reforzado durante el festival",daybus:"Autobús diurno H16 / H14 / 143 / 7 / 36",daybusDesc:"Desde distintas zonas del centro, 06:30–23:15",shuttle:"Bus lanzadera oficial",shuttleDesc:"~€2 por trayecto de medianoche al amanecer, Passeig Taulat → Plaça Catalunya. Reserva en AccessTicket app",walkDesc:"Paseo de ~60 min desde el centro por el Passeig Marítim con vistas al Mediterráneo",
    banH:"Objetos prohibidos",
    banItems:["Recipientes de vidrio","Cámara profesional/de vídeo (DSLR; no las compactas/analógicas)","Palos selfie","Drones","Mascotas (excepto perros guía)"],
    allowItems:["Comida (no en envases de vidrio)","Agua en botella de plástico ≤50cl sin tapón","Vaso de plástico propio ≤40cl","Cámara analógica, compacta o desechable","Bolso pequeño (tamaño A4)","Chubasquero / protector solar","Medicación con receta (con justificante)"],
    banLabel:"Prohibido",allowLabel:"Permitido",
    weatherH:"Previsión meteorológica",
    weatherNote:"Principios de junio en Barcelona suele ser soleado, 25–30°C de día, 18–22°C de noche. Lleva protector solar y una chaqueta ligera para las sesiones de madrugada.",
    tipsH:"Consejos prácticos",
    tips:["La pulsera AccessTicket debe activarse en la entrada; deja tiempo para la cola","Puntos de recarga de efectivo distribuidos por el recinto (solo pago con AccessTicket)","Fuentes de agua gratuitas en todo el recinto","El punto Nobody Is Normal ofrece asistencia de emergencia","Las fuentes de agua hacen cola en horas punta. Rellena la botella cuando cambies de escenario, no cuando tengas sed"],
    emergH:"Emergencias / Punto de ayuda",
    emergItems:["Teléfono de emergencias: 112","Punto de seguridad en la entrada principal y a los laterales de los escenarios principales","Si te pierdes del grupo: punto de encuentro delante del escenario principal"],
    ticketsH:"Entradas",
    ticketSalesBody:"Venta oficial: Fever (App Store/Google Play) y AccessTicket (pago a plazos). Las entradas son transferibles en AccessTicket si no han sido usadas ni vinculadas a actividades. No es necesario imprimir: se validan desde la app AccessTicket.",
    ticketTypesBody:"Solo hay pase de festival (3 días) o entradas de día. No hay entradas por concierto.",
    ticketQRBody:"El código QR solo permite un acceso. No compartas capturas de pantalla ni lo publiques en redes sociales.",
    minorsH:"Menores",
    minor12:"Hasta 12 años (incluido): entrada gratuita con ticket de Fever, acompañados por padre/madre o tutor legal (con documentación y entrada propia).",
    minor1315:"13–15 años: entrada de menores obligatoria. Deben ir acompañados por padre/madre o tutor legal (no hermanos ni otros familiares).",
    minor1617:"16–17 años: con entrada teen pueden entrar sin acompañante. Algunos conciertos en salas requieren 18+.",
    accessH:"Accesibilidad (PRM)",
    accessBody:"Las personas con movilidad reducida pueden acceder por carril rápido con un acompañante. Hay zonas reservadas en casi todos los escenarios y baños adaptados en todo el recinto.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Métodos de pago",
    payBody:"Tarjeta de crédito/débito (Visa y Mastercard; no se acepta American Express) y monedero AccessTicket.",
    lostH:"Objetos perdidos",
    lostBody:"Los objetos encontrados se llevan al punto de información exterior. Ve a cualquier punto de info o rellena el formulario. Tras el festival, los no reclamados van a la Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"FAQ oficial",faqLink:"Ver preguntas frecuentes oficiales",
    navHome:"Inicio",navSchedule:"Horario",navMap:"Mapa",navFavs:"Guardados",navInfo:"Info",navTheme:"Tema",navLang:"Idioma",
    showPast:"terminados",hidePast:"Ocultar pasados",more:"más",collapse:"colapsar",
    disclaimer:"Sitio no oficial creado por fans.<br>Sin afiliación con Primavera Sound S.L.<br>Todas las marcas pertenecen a sus respectivos propietarios.<br>Información orientativa; consulta la <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">web oficial</a>.<br>Sugerencias o correcciones:",
  },
  ca:{
    city:"Barcelona · Parc del Fòrum · Juny 2026",
    now:"▶ EN DIRECTE",next:"⏭ PRÒXIM",remaining:"restant",startsIn:"per començar",
    sort:"Ordre",byTime:"Hora",byName:"Nom",
    favs:"💖 Els meus favorits",noFavs:"Encara no tens favorits",
    headliner:"HEADLINER",live:"● EN DIRECTE",
    mapHint:"Pessiga per fer zoom · Toca l'escenari",reset:"Reinicia",noShows:"Avui no hi ha concerts",mapOfficial:"Veure el mapa oficial en alta resolució",
    myEmpty:"💖 Desa artistes\nper veure el teu itinerari personal aquí",myTitle:"El meu itinerari",conflict:"Solapament",
    opening:"Obertura",day1:"Dia 1",day2:"Dia 2",day3:"Dia 3",bits:"Bits",free:"Gratis",
    infoTitle:"Informació pràctica",
    doorsH:"Horaris d'obertura",doorsBody:"El Parc del Fòrum obre cada dia cap a les 16:00, els concerts continuen fins a les 05:00–06:00. El dimecres d'obertura (3/6) és gratuït des de les ~17:00.",
    transitH:"Com arribar-hi",metroLine:"Metro L4 (línia groga)",metroStop:"Parada El Maresme | Fòrum",
    nightbus:"Autobús nocturn N6",nightbusDesc:"Servei nocturn fins al centre (Pl. Catalunya) cada ~15 min, un cop tancat el metro",
    bikeDesc:"Aparcament de bicicletes gratuït al recinte",metroHours:"Dl–Dj 05:00–00:00 · Dv 05:00–02:00 · Ds servei continuat 24h",tramLine:"Tramvia T4 (Trambesòs)",tramStop:"Parada Fòrum · Servei reforçat durant el festival",daybus:"Autobusos diürns H16 / H14 / 143 / 7 / 36",daybusDesc:"Des de diverses zones del centre, 06:30–23:15",shuttle:"Bus llançadora oficial",shuttleDesc:"~2€ per trajecte de mitjanit a l'alba, Passeig Taulat → Plaça Catalunya. Reserva a l'app AccessTicket",walkDesc:"~60 min a peu des del centre per la rambla del mar amb vistes al Mediterrani",
    banH:"Objectes prohibits",
    banItems:["Recipients de vidre","Càmera professional/de vídeo (DSLR; compactes i analògiques OK)","Pals selfie","Drons","Mascotes (excepte gossos d'assistència)"],
    allowItems:["Menjar (no en recipients de vidre)","Aigua en ampolla de plàstic ≤ 50 cl (sense tap a l'entrada)","Got de plàstic propi ≤ 40 cl","Càmera analògica, compacta o d'un sol ús","Bossa petita (fins a mida A4)","Impermeable / protector solar","Medicació amb recepta (amb documentació)"],
    banLabel:"No permès",allowLabel:"Permès",
    weatherH:"Previsió meteorològica",
    weatherNote:"Els primers de juny a Barcelona sol fer sol, 25–30°C durant el dia i 18–22°C de nit. Porta protector solar i una jaqueta lleugera per als concerts de matinada.",
    tipsH:"Consells pràctics",
    tips:["La polsera AccessTicket s'ha d'activar a l'entrada — deixa temps per fer cua","Punts de recàrrega en efectiu distribuïts pel recinte (pagament AccessTicket)","Fonts d'aigua gratuïtes per tot el recinte","El punt Nobody Is Normal ofereix assistència d'emergència","Tot i que hi ha fonts d'aigua, fan llargues cues durant les hores punta. Omple l'ampolla quan canvies d'escenari, no quan tinguis set"],
    emergH:"Emergències / Punt d'ajuda",
    emergItems:["Telèfon d'emergències: 112","Punt de seguretat: a l'entrada principal i als laterals dels escenaris principals","Si et perds del grup: punt de trobada davant l'escenari principal"],
    ticketsH:"Entrades",
    ticketSalesBody:"Venda oficial: Fever (iOS/Android) i AccessTicket (pagament a terminis). Les entrades es poden cedir a AccessTicket si no han estat usades ni vinculades a activitats. No cal imprimir — es validen des de l'app AccessTicket.",
    ticketTypesBody:"Només hi ha abonaments de festival (3 dies) i entrades de dia. No hi ha entrades per concert.",
    ticketQRBody:"El codi QR només funciona un cop. No comparteixis captures de pantalla ni el publiquis a les xarxes socials.",
    minorsH:"Menors",
    minor12:"Fins a 12 anys (inclosos): entrada gratuïta amb tiquet de Fever, acompanyats per pare/mare o tutor legal (amb documentació i entrada pròpia).",
    minor1315:"13–15 anys: entrada de menors obligatòria. Han d'anar acompanyats per pare/mare o tutor legal (no germans ni altres familiars).",
    minor1617:"16–17 anys: amb entrada teen poden entrar sense acompanyant. Alguns espectacles en sala requereixen 18+.",
    accessH:"Accessibilitat (PMR)",
    accessBody:"Les persones amb mobilitat reduïda poden accedir per carril ràpid amb un acompanyant. Hi ha zones reservades a gairebé tots els escenaris i lavabos adaptats arreu del recinte.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Mètodes de pagament",
    payBody:"Targeta de crèdit/dèbit (Visa i Mastercard; no s'accepta American Express) i moneder AccessTicket.",
    lostH:"Objectes perduts",
    lostBody:"Els objectes trobats es porten al punt d'informació exterior. Ves a qualsevol punt d'informació o omple el formulari. Després del festival, els no reclamats van a la Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"Preguntes freqüents oficials",faqLink:"Veure les preguntes freqüents oficials",
    navHome:"Inici",navSchedule:"Horari",navMap:"Mapa",navFavs:"Preferits",navInfo:"Info",navTheme:"Tema",navLang:"Idioma",
    showPast:"acabats",hidePast:"Amaga els acabats",more:"més",collapse:"replegar",
    disclaimer:"Guia no oficial creada per fans.<br>Sense afiliació amb Primavera Sound S.L.<br>Totes les marques pertanyen als seus respectius propietaris.<br>Informació orientativa; consulta el <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">lloc web oficial</a>.<br>Comentaris o correccions:",
  },
  en:{
    city:"Barcelona · Parc del Fòrum · June 2026",
    now:"▶ NOW PLAYING",next:"⏭ UP NEXT",remaining:"left",startsIn:"to start",
    sort:"Sort",byTime:"Time",byName:"Name",
    favs:"💖 My Favourites",noFavs:"No saved artists yet",
    headliner:"HEADLINER",live:"● LIVE",
    mapHint:"Pinch to zoom · Tap stage to see shows",reset:"Reset",noShows:"No shows today",mapOfficial:"View official hi-res map",
    myEmpty:"💖 Save artists\nto see your personal lineup here",myTitle:"My lineup",conflict:"Clash",
    opening:"Opening",day1:"Day 1",day2:"Day 2",day3:"Day 3",bits:"Bits",free:"Free",
    infoTitle:"Practical Info",
    doorsH:"Opening hours",doorsBody:"Parc del Fòrum opens daily around 16:00, with sets running until 05:00–06:00. Wednesday opening day (3 June) is free from ~17:00.",
    transitH:"Getting there",metroLine:"Metro L4 (Yellow line)",metroStop:"El Maresme | Fòrum stop",
    nightbus:"Night bus N6",nightbusDesc:"Runs after metro closes, every ~15 min to city centre (Pl. Catalunya)",
    bikeDesc:"Free bike parking inside the venue",metroHours:"Mon–Thu 05:00–00:00 · Fri 05:00–02:00 · Sat 24h continuous",tramLine:"Tram T4",tramStop:"Fòrum stop · Extra services during festival days",daybus:"Day buses H16 / H14 / 143 / 7 / 36",daybusDesc:"From various city districts, 06:30–23:15",shuttle:"Official shuttle bus",shuttleDesc:"~€2/trip midnight to dawn, Passeig Taulat → Plaça Catalunya. Book via AccessTicket app",walkDesc:"~60 min walk from city centre along the beach promenade with sea views",
    banH:"Prohibited items",
    banItems:["Glass containers","Professional/video cameras (DSLR; compact & analogue OK)","Selfie sticks","Drones","Pets (except assistance dogs)"],
    allowItems:["Food (not in glass containers)","Water in plastic bottle ≤50cl (cap removed at gate)","Your own plastic cup ≤40cl","Analogue, compact or disposable cameras","Small bag (up to A4 size)","Raincoat / sunscreen","Prescription medication (with documentation)"],
    banLabel:"Not allowed",allowLabel:"Allowed",
    weatherH:"Weather forecast",
    weatherNote:"Early June in Barcelona is typically sunny, 25–30°C during the day and 18–22°C at night. Bring sunscreen and a light jacket for late-night sets.",
    tipsH:"Practical tips",
    tips:["Your AccessTicket wristband must be activated at the entrance — allow time to queue","Cash reload points are scattered around the venue (AccessTicket payment only)","Free water points throughout the venue","Nobody Is Normal safe space provides emergency assistance","Free water points get long queues at peak hours. Top up your bottle when moving between stages, not when you're already thirsty"],
    emergH:"Emergency / Help point",
    emergItems:["Emergency number: 112","Safety points at the main entrance and on both sides of the main stages","If separated from your group: meeting point in front of the main stage"],
    ticketsH:"Tickets",
    ticketSalesBody:"Official sales: Fever (iOS/Android) and AccessTicket (instalments). Tickets are transferable in AccessTicket if unused and not linked to any activity. No printing needed — validated via the AccessTicket app.",
    ticketTypesBody:"Only full festival passes (3 days) and single day tickets available. No single-concert tickets.",
    ticketQRBody:"The QR code only works once. Do not share screenshots or post it on social media.",
    minorsH:"Minors",
    minor12:"Up to 12 (inclusive): free entry with a Fever ticket, accompanied by a parent or legal guardian (with ID and their own ticket).",
    minor1315:"Ages 13–15: minors' ticket required. Must be accompanied by a parent or legal guardian — siblings or other relatives not permitted.",
    minor1617:"Ages 16–17: teen ticket, may enter unaccompanied. Some venue shows require 18+.",
    accessH:"Accessibility (PRM)",
    accessBody:"People with reduced mobility can use a fast-track entrance with one companion. Reserved viewing areas at most stages and adapted restrooms throughout the venue.",
    accessEmail:"accessibility@primaverasound.com",
    payH:"Payment methods",
    payBody:"Credit/debit cards (Visa & Mastercard; Amex not accepted) and the AccessTicket wallet.",
    lostH:"Lost & found",
    lostBody:"Found items are taken to the external info point. Visit any info point or fill in the lost & found form. After the festival, unclaimed items go to Guàrdia Urbana de Poblenou (Carrer d'Espronceda, 148).",
    faqH:"Official FAQ",faqLink:"View the full official FAQ",
    navHome:"Home",navSchedule:"Schedule",navMap:"Map",navFavs:"Saved",navInfo:"Info",navTheme:"Theme",navLang:"Language",
    showPast:"ended",hidePast:"Hide ended",more:"more",collapse:"collapse",
    disclaimer:"Unofficial fan-made guide.<br>Not affiliated with Primavera Sound S.L.<br>All trademarks belong to their respective owners.<br>Information for reference only; check the <a class=\"footer-link\" href=\"https://www.primaverasound.com/es/barcelona\" target=\"_blank\" rel=\"noopener\">official site</a>.<br>Feedback or corrections:",
  }
};

var curLang=localStorage.getItem("ps26_lang")||(function(){
  var ls=navigator.languages||[navigator.language||"en"];
  for(var i=0;i<ls.length;i++){var l=ls[i].toLowerCase();
    if(l==="ca"||l.startsWith("ca-"))return"ca";
    if(l==="zh"||l.startsWith("zh-"))return"zh";
    if(l==="es"||l.startsWith("es-"))return"es";
  }
  return"en";
})();
function t(k){return LANGS[curLang][k]||LANGS.zh[k]||k;}
function setLang(l){
  curLang=l;localStorage.setItem("ps26_lang",l);
  if(typeof vaTrack==='function')vaTrack('switch_language',{lang:l});
  applyLang();
  renderDayTabs();
  render();
  updateNowPlaying();
  if(typeof updateThemeToggleUI==='function')updateThemeToggleUI();
}
function applyLang(){
  document.querySelectorAll(".lang-btn,.home-lang-btn").forEach(function(b){b.classList.toggle("on",b.dataset.lang===curLang);});
  document.getElementById("lbl-city").textContent=t("city");
  document.getElementById("lbl-mapHint").textContent=t("mapHint");
  document.getElementById("lbl-reset").textContent=t("reset");
  document.getElementById("lbl-favs").textContent=t("favs");
  document.getElementById("lbl-sort").textContent=t("sort");
  document.querySelectorAll("[data-i]").forEach(function(el){el.textContent=t(el.dataset.i);});
  var footer=document.getElementById("app-footer");
  if(footer)footer.innerHTML=t("disclaimer")+' <a class="footer-mail" href="mailto:maxx7770101@gmail.com">maxx7770101@gmail.com</a>';
  if(curView==="info")renderInfo();
}